version: '3.9'

services:
  exporter:
    build:
      context: .
      dockerfile: build/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - config.yaml:/app/config.yaml
    environment:
      - PYTHONUNBUFFERED=1
