---
apiVersion: v1
kind: ConfigMap
metadata:
  name: acpi-exporter-config
  namespace: acpi-exporter
  labels:
    app.kubernetes.io/component: acpi-exporter-configmap
    app.kubernetes.io/name: acpi-exporter
data:
  config.yaml: |-
    port: 8000
    interval: 10
    namespace: "ACPI"
    subsystem: "exporter"
    log_level: "INFO"
    trace_errors: false
