---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: acpi-exporter
  namespace: acpi-exporter
  labels:
    app.kubernetes.io/component: acpi-exporter-daemonset
    app.kubernetes.io/name: acpi-exporter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: acpi-exporter-pod
      app.kubernetes.io/name: acpi-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/component: acpi-exporter-pod
        app.kubernetes.io/name: acpi-exporter
    spec:
      containers:
        - name: acpi-exporter
          image: ghcr.io/amirhnajafiz/acpi-exporter:v0.1.0
          imagePullPolicy: IfNotPresent
          env:
          - name: "NODE_NAME"
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          ports:
            - name: metrics
              containerPort: 8000
          volumeMounts:
            - name: sysclass
              mountPath: /sys/class
            - name: config
              mountPath: /app/src/config.yaml
              subPath: config.yaml
      volumes:
        - name: sysclass
          hostPath: /sys/class
        - name: config
          configMap:
            name: acpi-exporter-config
            items:
              - key: config.yaml
                path: config.yaml
