---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: acpi-exporter
  namespace: acpi-exporter
  labels:
    app.kubernetes.io/component: acpi-exporter-daemonset
    app.kubernetes.io/name: acpi-exporter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: acpi-exporter-pod
      app.kubernetes.io/name: acpi-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/component: acpi-exporter-pod
        app.kubernetes.io/name: acpi-exporter
    spec:
      tolerations:
        - key: "node-role.kubernetes.io/master"
          operator: "Equal"
          value: "master"
          effect: "NoSchedule"
      containers:
        - name: acpi-exporter
          image: ghcr.io/amirhnajafiz/acpi-exporter:v0.2.0
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
            readOnlyRootFilesystem: true
          env:
          - name: "NODE_NAME"
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          ports:
            - name: metrics
              containerPort: 8000
          volumeMounts:
            - name: sysclass
              mountPath: /sys/class
            - name: proc
              mountPath: /proc
            - name: config
              mountPath: /app/src/config.yaml
              subPath: config.yaml
      volumes:
        - name: sysclass
          hostPath:
            path: /sys/class
            type: Directory
        - name: proc
          hostPath:
            path: /proc
            type: Directory
        - name: config
          configMap:
            name: acpi-exporter-config
            items:
              - key: config.yaml
                path: config.yaml
