apiVersion: v1
kind: Pod
metadata:
  name: acpi-exporter
spec:
  containers:
    - name: acpi-exporter
      image: your‑registry/acpi-exporter:latest
      ports:
        - name: metrics
          containerPort: 8000
      volumeMounts:
        - name: config
          mountPath: /app/src/config.yaml
          subPath: config.yaml
  volumes:
    - name: config
      configMap:
        name: acpi-exporter-config
        items:
          - key: config.yaml
            path: config.yaml

