---
apiVersion: v1
kind: Pod
metadata:
  name: acpi-exporter
  namespace: acpi-exporter
  labels:
    app.kubernetes.io/component: acpi-exporter-pod
    app.kubernetes.io/name: acpi-exporter
spec:
  containers:
    - name: acpi-exporter
      image: ajoukov/acpi-exporter:latest
      ports:
        - name: metrics
          containerPort: 8000
      volumeMounts:
        - name: sysclass
          mountPath: /sys/class
        - name: config
          mountPath: /app/src/config.yaml
          subPath: config.yaml
  volumes:
    - name: sysclass
      hostPath: /sys/class
    - name: config
      configMap:
        name: acpi-exporter-config
        items:
          - key: config.yaml
            path: config.yaml
