---
apiVersion: v1
kind: Service
metadata:
  name: acpi-exporter-metrics
  namespace: acpi-exporter
  labels:
    app.kubernetes.io/component: acpi-exporter-service
    app.kubernetes.io/name: acpi-exporter
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    app.kubernetes.io/component: acpi-exporter-pod
    app.kubernetes.io/name: acpi-exporter
