---
apiVersion: v1
kind: Service
metadata:
  name: acpi-exporter-metrics
  namespace: acpi-exporter
  labels:
    app: acpi-exporter
    component: service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    app: acpi-exporter
    component: pod
